servers:
  browser-tools:
    name: "Browser Tools MCP"
    description: "Capture browser console logs, network activity, and debugging information"
    runtime: docker
    image: node:20-alpine
    command: npx
    args:
      - "-y"
      - "@agentdeskai/browser-tools-mcp"
    ports:
      - "3025:3025"
    environment:
      - NODE_ENV=development
    volumes:
      - "${HOME}/.mcp/browser-logs:/logs:rw"
    capabilities:
      - tools
      - resources

  # Chrome Extension Bridge for WebSocket communication
  chrome-bridge:
    name: "Chrome Extension Bridge"
    description: "WebSocket bridge for Chrome extension communication"
    runtime: docker
    image: node:20-alpine
    command: node
    args:
      - "/app/server.js"
    ports:
      - "3333:3333"
    volumes:
      - "./chrome-bridge:/app:ro"
    environment:
      - WS_PORT=3333
    capabilities:
      - tools

gateway:
  port: 8080
  transport: streaming
  auth:
    enabled: false
  cors:
    enabled: true
    origins:
      - "http://localhost:*"
      - "https://claude.ai"