all:
  hosts:
    frontend:
      # conecta no IP que o Terraform passa
      ansible_host: '18.221.255.168'
      ansible_user: ubuntu
      ansible_connection: ssh
      ansible_port: 22
      ansible_ssh_private_key_file: '~/.ssh/revalida-key'
