---
- name: Deploy Frontend Next.js (produção)
  hosts: frontend
  become: true

  vars:
    app_dir: /home/ubuntu/frontend
    repo_url: https://github.com/wbrunovieira/revalidaItaliaFrontNext.git

  tasks:
    - name: Ensure /home/ubuntu/frontend exists
      file:
        path: '{{ app_dir }}'
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Log debug info
      shell:
        echo "[DEBUG] Entrou na playbook $(date)" >>
        /home/ubuntu/deploy.log

    # ─── Preparação do sistema ────────────────────────────────────────────────
    - name: Atualiza cache do apt e instala pacotes básicos
      apt:
        update_cache: yes
        name:
          - curl
          - git
          - build-essential
          - python3
          - python3-apt
        state: present

    - name: Instala Node.js e npm (via NodeSource)
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
        apt-get install -y nodejs
      args:
        executable: /bin/bash
    # ─── Fim preparação ───────────────────────────────────────────────────────

    - name: Instala PM2 globalmente
      npm:
        name: pm2
        global: yes
        state: present
      become: yes

    - name: Clona ou atualiza o repositório do frontend
      git:
        repo: '{{ repo_url }}'
        dest: '{{ app_dir }}'
        version: main
        force: yes
      become_user: ubuntu

    - name: Instala dependências do projeto
      command: npm install
      args:
        chdir: '{{ app_dir }}'
      become_user: ubuntu

    - name: Realiza build do projeto
      command: npm run build
      args:
        chdir: '{{ app_dir }}'
      become_user: ubuntu

    - name: Inicia aplicação com PM2
      command: pm2 start npm --name frontend -- start
      args:
        chdir: '{{ app_dir }}'
      become_user: ubuntu

    - name: Salva configuração do PM2
      command: pm2 save
      become_user: ubuntu

    - name: Ativa startup do PM2 no boot
      shell: |
        pm2 startup systemd -u ubuntu --hp /home/ubuntu
        pm2 save
      args:
        executable: /bin/bash
      become_user: ubuntu
