---
- name: Deploy Frontend Next.js (produção)
  hosts: frontend
  become: true

  vars:
    app_dir: /home/ubuntu/frontend
    repo_url: https://github.com/wbrunovieira/revalidaItaliaFrontNext.git

  tasks:
    - name: Ensure {{ app_dir }} exists
      file:
        path: '{{ app_dir }}'
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Wait for apt to be available (lock released)
      shell: |
        while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
          echo "Waiting for other apt processes to finish...";
          sleep 3;
        done
      changed_when: false

    - name: Update apt and install base packages
      apt:
        update_cache: yes
        name:
          - curl
          - git
          - build-essential
          - python3
          - python3-apt
        state: present

    - name: Install Node.js & npm (NodeSource)
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
        apt-get install -y nodejs
      args:
        executable: /bin/bash

    - name: Install PM2 globally
      npm:
        name: pm2
        global: yes
        state: present

    - name: Clone or update repo
      git:
        repo: '{{ repo_url }}'
        dest: '{{ app_dir }}'
        version: main
        force: yes
      become_user: ubuntu

    - name: Debug NEXT_PUBLIC_API_URL antes de gerar .env
      debug:
        msg: 'NEXT_PUBLIC_API_URL={{ NEXT_PUBLIC_API_URL }}'

    - name: Generate .env for Next.js
      template:
        src: 'templates/.env.prod.j2'
        dest: '{{ app_dir }}/.env'
        owner: ubuntu
        group: ubuntu
        mode: '0600'
      become_user: ubuntu

    - name: Show generated .env
      command: cat {{ app_dir }}/.env
      register: env_prod
      become_user: ubuntu

    - name: Debug conteúdo de .env
      debug:
        var: env_prod.stdout_lines

    - name: Stop and delete PM2 process if exists
      shell: |
        pm2 delete frontend || true
        pm2 flush
      args:
        chdir: '{{ app_dir }}'
      become_user: ubuntu

    - name:
        Force kill any process using port 3000 (even
        orphaned)
      shell: |
        fuser -k 3000/tcp || true
      become_user: ubuntu
      ignore_errors: yes

    - name: Wait until port 3000 is free
      shell: |
        while fuser 3000/tcp >/dev/null 2>&1; do
          echo "Port 3000 still in use... waiting.";
          sleep 2;
        done
      changed_when: false
      become_user: ubuntu

    - name: Install project dependencies
      command: npm install
      args:
        chdir: '{{ app_dir }}'
      become_user: ubuntu

    - name: Build project
      command: npm run build
      args:
        chdir: '{{ app_dir }}'
      become_user: ubuntu

    - name: Start frontend in PM2
      shell: |
        pm2 start npm --name frontend -- start -- -p 3000 -H 0.0.0.0
        pm2 save
      args:
        chdir: '{{ app_dir }}'
      become_user: ubuntu

    - name: Setup PM2 startup at boot
      shell: |
        pm2 startup systemd -u ubuntu --hp /home/ubuntu
        pm2 save
      args:
        executable: /bin/bash
      become_user: ubuntu
